/**
 * Inline text helpers for GFM pipe-table cells.
 *
 * `sanitizeCellText` flattens text so it is safe inside a cell; `renderCellText`
 * renders the inline-markdown subset a cell displays while the raw markdown
 * stays the source of truth.
 *
 * Why this file carries its own URL policy instead of calling `renderMarkdown`
 * --------------------------------------------------------------------------
 * A cell needs INLINE-ONLY rendering: the block-level `renderMarkdown` SSOT
 * (`@md-bundle/renderer`) wraps its output in `<p>`/block elements that would
 * break the table layout. The scheme allow-list below therefore MIRRORS the
 * renderer SSOT (`packages/renderer/src/markdown.ts`, `DANGEROUS_URL_RE`) so
 * both paths agree on which URLs may execute.
 *
 * A dependency leaf: the table widget (staging/render) and the anchored insert
 * menu (commands) reuse it without importing each other.
 */

/**
 * Flatten text so it is safe inside a GFM pipe-table cell.
 *
 * A newline would start a new block and a raw `|` would add a column, either of
 * which silently corrupts the table structure on the next parse. Both are
 * flattened to spaces: losing a character beats corrupting the document.
 */
export function sanitizeCellText(text: string): string {
  return text.replace(/\r?\n/g, ' ').replace(/\|/g, ' ');
}

/**
 * Cell background convention (ticket #328).
 *
 * A cell background is stored in the markdown source as the cell's whole text
 * wrapped in the SAME raw-HTML span the text-color system uses:
 *
 *   | <span class="mdb-bg-blue">hello</span> | ...
 *
 * This keeps the markdown a valid GFM pipe table (no column/row syntax is
 * invented) and reuses the existing `mdb-bg-*` classes, so the background
 * survives a reload and renders in preview. The table widget detects the exact
 * shape and paints the `<td>`/`<th>` instead of showing the span markup.
 */
const BACKGROUND_SPAN_RE =
  /^<span class="(mdb-bg-(?:red|blue|green|orange|purple))">([\s\S]*)<\/span>$/;

export interface ParsedCellBackground {
  /** The `mdb-bg-*` span class. */
  colorClass: string;
  /** The visible text without the span wrapper. */
  inner: string;
}

/** Parse a cell whose entire text is one background span; null otherwise. */
export function parseCellBackground(text: string): ParsedCellBackground | null {
  const match = BACKGROUND_SPAN_RE.exec(text);
  if (!match) return null;
  return { colorClass: match[1], inner: match[2] };
}

/** Strip any background span wrapper, returning the bare cell text. */
export function stripCellBackground(text: string): string {
  return parseCellBackground(text)?.inner ?? text;
}

// ── URL scheme allow-list (mirrors the renderer SSOT) ────────────────────
// `DANGEROUS_URL_RE` in `packages/renderer/src/markdown.ts` strips `javascript:`
// and `vbscript:`; this allow-list is the stricter editor-side mirror: ONLY the
// schemes below (or no scheme at all) may ever reach `href`.
const SAFE_SCHEMES = new Set(['http', 'https', 'mailto']);
const URL_SCHEME_RE = /^([a-z][a-z0-9+.-]*):/i;

/**
 * Drop every space and C0 control (code point ≤ 0x20) before the scheme check.
 *
 * Browsers strip these from a URL before parsing it, so the check must see the
 * same string — otherwise `java\nscript:` would pass as a scheme-less "relative"
 * URL and still execute. Done by code point rather than a regex so the source
 * holds no control characters.
 */
function stripControlsForSchemeCheck(url: string): string {
  let normalized = '';
  for (const char of url) {
    if (char.charCodeAt(0) > 0x20) normalized += char;
  }
  return normalized;
}

/** True when `url` may become an `href` (allow-list, never a deny-list). */
function isSafeHref(url: string): boolean {
  const scheme = URL_SCHEME_RE.exec(stripControlsForSchemeCheck(url))?.[1];
  if (!scheme) return true; // no scheme → relative path or fragment
  return SAFE_SCHEMES.has(scheme.toLowerCase());
}

/**
 * Sentinel that survives the inline transforms; slots a link target out.
 * A private-use code point, so it cannot collide with ordinary cell text or be
 * rewritten by the emphasis/code passes. Step 4 always resolves every slot.
 */
const URL_SLOT = '\uE000';

/**
 * Render inline markdown in cell text to HTML.
 *
 * Used by the table widget to display formatted text in cells while keeping
 * the raw markdown as the source of truth. Handles **bold**, *italic*, `code`,
 * ~~strike~~, [link](url). HTML in the source text is escaped first, so only
 * tags generated by this function appear in the output.
 */
export function renderCellText(text: string): string {
  const background = parseCellBackground(text);
  const inner = background ? background.inner : text;

  // Step 1: escape HTML entities FIRST — this is the security boundary.
  // Only the tags we explicitly generate below will be real HTML in the output.
  const escaped = inner
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');

  // Step 2: slot link targets out BEFORE any inline transform. Emphasis
  // (`_…_`, `*…*`) must not rewrite a URL: `[x](https://a_b_c.com)` keeps its
  // literal underscores, and a `*` in a path never becomes `<em>`.
  const targets: string[] = [];
  const stashed = escaped.replace(
    /\[([^\]]+)\]\(([^)]+)\)/g,
    (_match, label: string, url: string) => {
      targets.push(url);
      return `[${label}](${URL_SLOT}${targets.length - 1}${URL_SLOT})`;
    },
  );

  // Step 3: apply markdown transforms to the escaped, URL-free text. The
  // replacement strings contain literal HTML tags we intend to emit.
  const rendered = stashed
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/(?<!\*)\*(?!\*)(.+?)(?<!\*)\*(?!\*)/g, '<em>$1</em>')
    .replace(/_([^_]+?)_/g, '<em>$1</em>')
    .replace(/`(.+?)`/g, '<code>$1</code>')
    .replace(/~~(.+?)~~/g, '<del>$1</del>');

  // Step 4: re-emit anchors, sending every target through the scheme
  // allow-list. An unsafe scheme (javascript:, vbscript:, data:, file:, …)
  // never reaches `href`: the anchor is dropped and the label stays as text.
  return rendered.replace(
    new RegExp(`\\[([^\\]]+)\\]\\(${URL_SLOT}(\\d+)${URL_SLOT}\\)`, 'g'),
    (_match, label: string, index: string) => {
      const url = targets[Number(index)] ?? '';
      if (!isSafeHref(url)) return label;
      return `<a href="${url}" target="_blank" rel="noopener noreferrer">${label}</a>`;
    },
  );
}
